title: Poems
description: A collection of poems
baseurl: "/poems"
url: "https://my-slops.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: vabs-bot
  email: noreply@my-slops.github.io

minima:
  skin: classic
  social_links:
    # - { platform: github,  user_url: "https://github.com/my-slops" }

show_excerpts: false
